import React from 'react';
import { LegalLayout } from '../components/legal/LegalLayout';

export const PrivacyPolicy = () => {
  return (
    <LegalLayout
      title="Privacy Policy (Draft)"
      summary="Information on how the Campital website operates, what data is collected in frontend forms, and our zero-backend approach."
    >
      <h3>1. Overview & Frontend Architecture</h3>
      <p>
        Campital operates this static web portal to introduce startups, incubators, SMEs, and capital partners to our pipeline. This policy transparently explains our data collection and handling practices across the website.
      </p>

      <h3>2. Information Requested in Forms</h3>
      <p>
        When you choose to initiate an inquiry or funding application through our interactive forms, we request the minimum necessary contact information:
      </p>
      <ul>
        <li><strong>Full Name:</strong> To address you and structure the inquiry.</li>
        <li><strong>Email Address:</strong> To establish contact.</li>
        <li><strong>Organization / Venture / University Name:</strong> To contextualize the applicant or partner.</li>
        <li><strong>Track / Partner Category:</strong> To route the inquiry to the appropriate discovery pipeline.</li>
        <li><strong>Message / Summary:</strong> Background information provided voluntarily to describe your venture or partnership intent.</li>
      </ul>

      <h3>3. Zero-Backend & Mailto Implementation</h3>
      <p>
        <strong>No Backend Storage:</strong> This website is built as a static application with no centralized database, backend server, or third-party form-collection service (e.g., Formspree, EmailJS).
      </p>
      <p>
        <strong>User-Initiated Transmission:</strong> Clicking "Open Email Draft" or "Copy Email Details" compiles your form input into a structured <code>mailto:</code> link or formatted clipboard text. The actual transmission of the email is handled exclusively by your local email client (such as Gmail, Apple Mail, or Microsoft Outlook) when you manually choose to send the email.
      </p>
      <p>
        <strong>No Persistent Browser Storage:</strong> We do not store your entered form inputs in <code>localStorage</code>, <code>sessionStorage</code>, or cookies. If you navigate away or refresh the page, the form fields reset.
      </p>

      <h3>4. Cookies & Analytics</h3>
      <p>
        This Phase 1 website does not deploy advertising trackers, profiling cookies, or invasive user-tracking scripts. Standard hosting access logs generated by web servers (IP address, user agent) are handled according to hosting infrastructure standards.
      </p>

      <h3>5. External Links & Services</h3>
      <p>
        Our website may contain links to third-party services (such as partner websites or your local email software). We do not control and are not responsible for the privacy policies or practices of external platforms.
      </p>

      <h3>6. Changes & Legal Review</h3>
      <p>
        This draft policy is maintained for Phase 1 web operations. A comprehensive privacy policy will be finalized and published prior to full public commercial launch.
      </p>
    </LegalLayout>
  );
};
